# -*- coding: utf-8 -*-
"""Student performance analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BXgyuWZ2nT-OW5wFSdDnh8MBC6u-PXCX
"""

import numpy as np
import pandas as pd

"""Import dataset

"""

df = pd.read_csv("StudentPerformanceFactors.csv")

df.head(10)

print(df.dtypes)

df = df.drop(['Tutoring_Sessions' , 'Peer_Influence' , 'Distance_from_Home' ], axis=1)

"""One-Hot Coding"""

df = pd.get_dummies(
    df,
    columns=df.select_dtypes(include=['object','category']).columns,
    dtype=int
)

df

"""Splitting Data into Training and Testing"""

from sklearn.model_selection import train_test_split

X = df.drop('Exam_Score', axis=1)
y = df['Exam_Score']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0
)

"""Modeling "Decision Tree"
"""

from sklearn.tree import DecisionTreeRegressor

model_dt = DecisionTreeRegressor(
    max_depth=10,
    min_samples_split=5,
    random_state=42
)

model_dt.fit(X_train, y_train)

y_pred = model_dt.predict(X_test)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

"""Modeling "XgBoost"
"""

from xgboost import XGBRegressor

"""Hyperparameter tunning for "XgBoost"
"""

from sklearn.model_selection import RandomizedSearchCV

model = XGBRegressor(random_state=42)

params = {
    'n_estimators': [100,200,300,500],
    'max_depth': [3,4,5,6,7],
    'learning_rate': [0.01,0.05,0.1],
    'subsample': [0.7,0.8,1.0]
}

search = RandomizedSearchCV(
    model,
    params,
    n_iter=20,
    cv=5,
    scoring='r2',
    random_state=42
)

search.fit(X_train, y_train)

print(search.best_params_)

"""Re-train Model with new Parameters"""

model = XGBRegressor(
    n_estimators= 500,
    learning_rate=0.05,
    max_depth=3,
    random_state=0,
    subsample = 0.7
)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)